DROP DATABASE IF EXISTS prueba;
CREATE DATABASE prueba;

USE prueba;


CREATE TABLE PLAYER(
	ID INT NOT NULL,
	USERNAME VARCHAR(20) NOT NULL,
	PASSWORD VARCHAR(20) NOT NULL,
	WIN_GAMES INT,
	LOST_GAMES INT,
	TOTAL_GAMES INT,
	PRIMARY KEY(ID)
)ENGINE=InnoDB;

CREATE TABLE GAME(	
	ID INT NOT NULL,
	ID_PLY1 INT NOT NULL,
	ID_PLY2 INT NOT NULL,
	DURATION INT,
	DATE INT,
	HOUR INT,
	PRIMARY KEY(ID)
)ENGINE=InnoDB;

CREATE TABLE BRIDGE(	
	ID_GA INT NOT NULL,
	ID_PLY1 INT NOT NULL,
	ID_PLY2 INT NOT NULL,
	FOREIGN KEY(ID_PLY1) REFERENCES PLAYER (ID),
	FOREIGN KEY(ID_PLY2) REFERENCES PLAYER (ID),
	FOREIGN KEY(ID_GA) REFERENCES GAME(ID),
	PRIMARY KEY(ID_GA)
)ENGINE=InnoDB;


INSERT INTO PLAYER VALUES(1,'Sergi','sergi123',2,3,5);
INSERT INTO PLAYER VALUES(2,'Ramon','ramon453',5,0,5);
INSERT INTO PLAYER VALUES(3,'Pepe','pepe111',8,2,10);
INSERT INTO PLAYER VALUES(4,'Ferran','ferran178',5,3,8);
INSERT INTO PLAYER VALUES(5,'Esther','estermens',9,3,12);


INSERT INTO GAME VALUES(1,1,2,15,120221,1232);
INSERT INTO GAME VALUES(2,2,3,23,120221,1635);
INSERT INTO GAME VALUES(3,3,4,21,170621,1804);
INSERT INTO GAME VALUES(4,4,2,45,170621,1902);
INSERT INTO GAME VALUES(5,4,3,32,170621,2001);


INSERT INTO BRIDGE VALUES(1,1,2);
INSERT INTO BRIDGE VALUES(2,2,3);
INSERT INTO BRIDGE VALUES(3,3,4);
INSERT INTO BRIDGE VALUES(4,4,2);
INSERT INTO BRIDGE VALUES(5,4,3);


SELECT PLAYER.WIN_GAMES,PLAYER.USERNAME FROM PLAYER;